// <auto-generated />
using System;
using HotelDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApp.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20250916202507_Admin")]
    partial class Admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelDb.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HotelDb.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservationId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HotelDb.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Amenities = "Free Wi-Fi, Air Conditioning, Smart TV, Workspace, Wardrobe, Mini-bar, King-size bed, Shower",
                            Capacity = 2,
                            Description = "Cozy single room with a balcony and city view.",
                            Number = "101",
                            Price = 4000.0,
                            Status = "Free",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 2,
                            Amenities = "Free Wi-Fi, Air Conditioning, Coffee machine, Smart TV, Workspace, Wardrobe, Mini-bar, 2x King-size bed, Shower, 2x Sofa, Mini kitchen, Second floor",
                            Capacity = 4,
                            Description = "Spacious double room with modern design and large beds.",
                            Number = "202",
                            Price = 7500.0,
                            Status = "Free",
                            Type = "Executive"
                        },
                        new
                        {
                            RoomId = 3,
                            Amenities = "Free Wi-Fi, Air Conditioning, Coffee machine, Smart TV, Luxury workspace, Wardrobe, Private bar, King-size bed 2x, Luxury sofa, Luxury second floor,  Jacuzzi, Piano",
                            Capacity = 2,
                            Description = "Luxury presidential suite with premium facilities and panoramic city view.",
                            Number = "303",
                            Price = 10500.0,
                            Status = "Booked",
                            Type = "Presidential"
                        },
                        new
                        {
                            RoomId = 4,
                            Amenities = "Free Wi-Fi, Air Conditioning, Smart TV, Workspace, Wardrobe, Mini-bar, King-size bed, Shower",
                            Capacity = 2,
                            Description = "Comfortable single room with a minimalist interior, perfect for short stays.",
                            Number = "104",
                            Price = 4000.0,
                            Status = "Booked",
                            Type = "Deluxe"
                        },
                        new
                        {
                            RoomId = 5,
                            Amenities = "Free Wi-Fi, Air Conditioning, Coffee machine, Smart TV, Workspace, Wardrobe, Mini-bar, 2x King-size bed, Shower, 2x Sofa, Mini kitchen, Second floor",
                            Capacity = 4,
                            Description = "Modern double room with bright colors and a relaxing atmosphere.",
                            Number = "205",
                            Price = 7500.0,
                            Status = "Free",
                            Type = "Executive"
                        },
                        new
                        {
                            RoomId = 6,
                            Amenities = "Free Wi-Fi, Air Conditioning, Coffee machine, Smart TV, Luxury workspace, Wardrobe, Private bar, King-size bed 2x, Luxury sofa, Luxury second floor,  Jacuzzi, Piano",
                            Capacity = 2,
                            Description = "Exclusive presidential suite with luxury furniture, private bar and Jacuzzi.",
                            Number = "306",
                            Price = 10500.0,
                            Status = "Free",
                            Type = "Presidential"
                        });
                });

            modelBuilder.Entity("HotelDb.Models.RoomImage", b =>
                {
                    b.Property<int>("RoomImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("RoomImageId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomImages");

                    b.HasData(
                        new
                        {
                            RoomImageId = 1,
                            ImageUrl = "/images/rooms/101_1.jpg",
                            RoomId = 1
                        },
                        new
                        {
                            RoomImageId = 2,
                            ImageUrl = "/images/rooms/101_2.jpg",
                            RoomId = 1
                        },
                        new
                        {
                            RoomImageId = 3,
                            ImageUrl = "/images/rooms/202_1.jpg",
                            RoomId = 2
                        },
                        new
                        {
                            RoomImageId = 4,
                            ImageUrl = "/images/rooms/202_2.jpg",
                            RoomId = 2
                        },
                        new
                        {
                            RoomImageId = 20,
                            ImageUrl = "/images/rooms/202_3.jpg",
                            RoomId = 2
                        },
                        new
                        {
                            RoomImageId = 5,
                            ImageUrl = "/images/rooms/303_1.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            RoomImageId = 6,
                            ImageUrl = "/images/rooms/303_2.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            RoomImageId = 17,
                            ImageUrl = "/images/rooms/303_6.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            RoomImageId = 18,
                            ImageUrl = "/images/rooms/303_4.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            RoomImageId = 19,
                            ImageUrl = "/images/rooms/303_5.jpg",
                            RoomId = 3
                        },
                        new
                        {
                            RoomImageId = 8,
                            ImageUrl = "/images/rooms/104_1.jpg",
                            RoomId = 4
                        },
                        new
                        {
                            RoomImageId = 9,
                            ImageUrl = "/images/rooms/104_2.jpg",
                            RoomId = 4
                        },
                        new
                        {
                            RoomImageId = 10,
                            ImageUrl = "/images/rooms/205_1.jpg",
                            RoomId = 5
                        },
                        new
                        {
                            RoomImageId = 11,
                            ImageUrl = "/images/rooms/205_2.jpg",
                            RoomId = 5
                        },
                        new
                        {
                            RoomImageId = 21,
                            ImageUrl = "/images/rooms/205_3.jpg",
                            RoomId = 5
                        },
                        new
                        {
                            RoomImageId = 12,
                            ImageUrl = "/images/rooms/306_1.jpg",
                            RoomId = 6
                        },
                        new
                        {
                            RoomImageId = 13,
                            ImageUrl = "/images/rooms/306_2.jpg",
                            RoomId = 6
                        },
                        new
                        {
                            RoomImageId = 14,
                            ImageUrl = "/images/rooms/306_3.jpg",
                            RoomId = 6
                        },
                        new
                        {
                            RoomImageId = 15,
                            ImageUrl = "/images/rooms/306_4.jpg",
                            RoomId = 6
                        },
                        new
                        {
                            RoomImageId = 16,
                            ImageUrl = "/images/rooms/306_5.jpg",
                            RoomId = 6
                        });
                });

            modelBuilder.Entity("HotelDb.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HotelDb.Models.Payment", b =>
                {
                    b.HasOne("HotelDb.Models.Reservation", "Reservation")
                        .WithOne("Payment")
                        .HasForeignKey("HotelDb.Models.Payment", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HotelDb.Models.Reservation", b =>
                {
                    b.HasOne("HotelDb.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelDb.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelDb.Models.RoomImage", b =>
                {
                    b.HasOne("HotelDb.Models.Room", "Room")
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HotelDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HotelDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HotelDb.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelDb.Models.Reservation", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("HotelDb.Models.Room", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("HotelDb.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
